### ISSUE TITLE
how did you downloaded ?

### ISSUE THREAD

**Issue by prashantgpt91** [0xc0d3r/HackerEarth#1]
Hey @0xc0d3r 
how did you downloaded all solutions from your hackerearth account?
Is it done manually? or an automated script to do the same?

Thanks

**Comment by 0xc0d3r** [comment]
I did all programs in my system and pushed to github. That's it.

**Comment by prashantgpt91** [comment]
ok, I thought, you would have downloaded or scraped
Thanks
